/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface MarketFactoryInterface extends Interface {
    getFunction(nameOrSignature: "createMarket" | "feeCollector" | "implementation" | "matchSettlement" | "owner" | "renounceOwnership" | "setFeeCollector" | "setImplementation" | "transferOwnership" | "usdc"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "FeeCollectorUpdated" | "ImplementationUpdated" | "MarketCreated" | "OwnershipTransferred"): EventFragment;

    encodeFunctionData(functionFragment: 'createMarket', values: [BytesLike, BigNumberish, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'feeCollector', values?: undefined): string;
encodeFunctionData(functionFragment: 'implementation', values?: undefined): string;
encodeFunctionData(functionFragment: 'matchSettlement', values?: undefined): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'setFeeCollector', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'setImplementation', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'usdc', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'createMarket', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'feeCollector', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'implementation', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'matchSettlement', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setFeeCollector', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setImplementation', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'usdc', data: BytesLike): Result;
  }

  
    export namespace FeeCollectorUpdatedEvent {
      export type InputTuple = [feeCollector: AddressLike];
      export type OutputTuple = [feeCollector: string];
      export interface OutputObject {feeCollector: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ImplementationUpdatedEvent {
      export type InputTuple = [implementation: AddressLike];
      export type OutputTuple = [implementation: string];
      export interface OutputObject {implementation: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace MarketCreatedEvent {
      export type InputTuple = [matchId: BytesLike, market: AddressLike, outcomesCount: BigNumberish, b: BigNumberish, feeBps: BigNumberish];
      export type OutputTuple = [matchId: string, market: string, outcomesCount: bigint, b: bigint, feeBps: bigint];
      export interface OutputObject {matchId: string, market: string, outcomesCount: bigint, b: bigint, feeBps: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface MarketFactory extends BaseContract {
    
    connect(runner?: ContractRunner | null): MarketFactory;
    waitForDeployment(): Promise<this>;

    interface: MarketFactoryInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    createMarket: TypedContractMethod<
      [matchId: BytesLike, outcomesCount: BigNumberish, bScore: BigNumberish, feeBps: BigNumberish, ],
      [string],
      'nonpayable'
    >
    

    
    feeCollector: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    implementation: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    matchSettlement: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    setFeeCollector: TypedContractMethod<
      [newFeeCollector: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    setImplementation: TypedContractMethod<
      [newImplementation: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    usdc: TypedContractMethod<
      [],
      [string],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'createMarket'): TypedContractMethod<
      [matchId: BytesLike, outcomesCount: BigNumberish, bScore: BigNumberish, feeBps: BigNumberish, ],
      [string],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'feeCollector'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'implementation'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'matchSettlement'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setFeeCollector'): TypedContractMethod<
      [newFeeCollector: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setImplementation'): TypedContractMethod<
      [newImplementation: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'usdc'): TypedContractMethod<
      [],
      [string],
      'view'
    >;

    getEvent(key: 'FeeCollectorUpdated'): TypedContractEvent<FeeCollectorUpdatedEvent.InputTuple, FeeCollectorUpdatedEvent.OutputTuple, FeeCollectorUpdatedEvent.OutputObject>;
getEvent(key: 'ImplementationUpdated'): TypedContractEvent<ImplementationUpdatedEvent.InputTuple, ImplementationUpdatedEvent.OutputTuple, ImplementationUpdatedEvent.OutputObject>;
getEvent(key: 'MarketCreated'): TypedContractEvent<MarketCreatedEvent.InputTuple, MarketCreatedEvent.OutputTuple, MarketCreatedEvent.OutputObject>;
getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;

    filters: {
      
      'FeeCollectorUpdated(address)': TypedContractEvent<FeeCollectorUpdatedEvent.InputTuple, FeeCollectorUpdatedEvent.OutputTuple, FeeCollectorUpdatedEvent.OutputObject>;
      FeeCollectorUpdated: TypedContractEvent<FeeCollectorUpdatedEvent.InputTuple, FeeCollectorUpdatedEvent.OutputTuple, FeeCollectorUpdatedEvent.OutputObject>;
    

      'ImplementationUpdated(address)': TypedContractEvent<ImplementationUpdatedEvent.InputTuple, ImplementationUpdatedEvent.OutputTuple, ImplementationUpdatedEvent.OutputObject>;
      ImplementationUpdated: TypedContractEvent<ImplementationUpdatedEvent.InputTuple, ImplementationUpdatedEvent.OutputTuple, ImplementationUpdatedEvent.OutputObject>;
    

      'MarketCreated(bytes32,address,uint8,uint256,uint16)': TypedContractEvent<MarketCreatedEvent.InputTuple, MarketCreatedEvent.OutputTuple, MarketCreatedEvent.OutputObject>;
      MarketCreated: TypedContractEvent<MarketCreatedEvent.InputTuple, MarketCreatedEvent.OutputTuple, MarketCreatedEvent.OutputObject>;
    

      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    
    };
  }