/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface MatchSettlementInterface extends Interface {
    getFunction(nameOrSignature: "bondAmount" | "bondToken" | "clearDispute" | "disputeOutcome" | "disputeWindow" | "finalOutcome" | "finalizeOutcome" | "finalized" | "getOutcome" | "proposals" | "proposeOutcome" | "proposerSigner"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "DisputeCleared" | "OutcomeDisputed" | "OutcomeFinalized" | "OutcomeProposed"): EventFragment;

    encodeFunctionData(functionFragment: 'bondAmount', values?: undefined): string;
encodeFunctionData(functionFragment: 'bondToken', values?: undefined): string;
encodeFunctionData(functionFragment: 'clearDispute', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'disputeOutcome', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'disputeWindow', values?: undefined): string;
encodeFunctionData(functionFragment: 'finalOutcome', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'finalizeOutcome', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'finalized', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'getOutcome', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'proposals', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'proposeOutcome', values: [BytesLike, BigNumberish, BytesLike, BytesLike]): string;
encodeFunctionData(functionFragment: 'proposerSigner', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'bondAmount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'bondToken', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'clearDispute', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'disputeOutcome', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'disputeWindow', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'finalOutcome', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'finalizeOutcome', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'finalized', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getOutcome', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'proposals', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'proposeOutcome', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'proposerSigner', data: BytesLike): Result;
  }

  
    export namespace DisputeClearedEvent {
      export type InputTuple = [matchId: BytesLike];
      export type OutputTuple = [matchId: string];
      export interface OutputObject {matchId: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OutcomeDisputedEvent {
      export type InputTuple = [matchId: BytesLike, disputer: AddressLike];
      export type OutputTuple = [matchId: string, disputer: string];
      export interface OutputObject {matchId: string, disputer: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OutcomeFinalizedEvent {
      export type InputTuple = [matchId: BytesLike, outcome: BigNumberish];
      export type OutputTuple = [matchId: string, outcome: bigint];
      export interface OutputObject {matchId: string, outcome: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OutcomeProposedEvent {
      export type InputTuple = [matchId: BytesLike, outcome: BigNumberish, proposer: AddressLike, proposedAt: BigNumberish, dataHash: BytesLike, codeCommitHash: BytesLike];
      export type OutputTuple = [matchId: string, outcome: bigint, proposer: string, proposedAt: bigint, dataHash: string, codeCommitHash: string];
      export interface OutputObject {matchId: string, outcome: bigint, proposer: string, proposedAt: bigint, dataHash: string, codeCommitHash: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface MatchSettlement extends BaseContract {
    
    connect(runner?: ContractRunner | null): MatchSettlement;
    waitForDeployment(): Promise<this>;

    interface: MatchSettlementInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    bondAmount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    bondToken: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    clearDispute: TypedContractMethod<
      [matchId: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    disputeOutcome: TypedContractMethod<
      [matchId: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    disputeWindow: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    finalOutcome: TypedContractMethod<
      [arg0: BytesLike, ],
      [bigint],
      'view'
    >
    

    
    finalizeOutcome: TypedContractMethod<
      [matchId: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    finalized: TypedContractMethod<
      [arg0: BytesLike, ],
      [boolean],
      'view'
    >
    

    
    getOutcome: TypedContractMethod<
      [matchId: BytesLike, ],
      [[boolean, bigint] & {isFinalized: boolean, outcome: bigint }],
      'view'
    >
    

    
    proposals: TypedContractMethod<
      [arg0: BytesLike, ],
      [[bigint, string, string, bigint, boolean, string, string] & {outcome: bigint, proposer: string, disputer: string, proposedAt: bigint, disputed: boolean, dataHash: string, codeCommitHash: string }],
      'view'
    >
    

    
    proposeOutcome: TypedContractMethod<
      [matchId: BytesLike, outcome: BigNumberish, dataHash: BytesLike, codeCommitHash: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    proposerSigner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'bondAmount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'bondToken'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'clearDispute'): TypedContractMethod<
      [matchId: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'disputeOutcome'): TypedContractMethod<
      [matchId: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'disputeWindow'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'finalOutcome'): TypedContractMethod<
      [arg0: BytesLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'finalizeOutcome'): TypedContractMethod<
      [matchId: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'finalized'): TypedContractMethod<
      [arg0: BytesLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'getOutcome'): TypedContractMethod<
      [matchId: BytesLike, ],
      [[boolean, bigint] & {isFinalized: boolean, outcome: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'proposals'): TypedContractMethod<
      [arg0: BytesLike, ],
      [[bigint, string, string, bigint, boolean, string, string] & {outcome: bigint, proposer: string, disputer: string, proposedAt: bigint, disputed: boolean, dataHash: string, codeCommitHash: string }],
      'view'
    >;
getFunction(nameOrSignature: 'proposeOutcome'): TypedContractMethod<
      [matchId: BytesLike, outcome: BigNumberish, dataHash: BytesLike, codeCommitHash: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'proposerSigner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;

    getEvent(key: 'DisputeCleared'): TypedContractEvent<DisputeClearedEvent.InputTuple, DisputeClearedEvent.OutputTuple, DisputeClearedEvent.OutputObject>;
getEvent(key: 'OutcomeDisputed'): TypedContractEvent<OutcomeDisputedEvent.InputTuple, OutcomeDisputedEvent.OutputTuple, OutcomeDisputedEvent.OutputObject>;
getEvent(key: 'OutcomeFinalized'): TypedContractEvent<OutcomeFinalizedEvent.InputTuple, OutcomeFinalizedEvent.OutputTuple, OutcomeFinalizedEvent.OutputObject>;
getEvent(key: 'OutcomeProposed'): TypedContractEvent<OutcomeProposedEvent.InputTuple, OutcomeProposedEvent.OutputTuple, OutcomeProposedEvent.OutputObject>;

    filters: {
      
      'DisputeCleared(bytes32)': TypedContractEvent<DisputeClearedEvent.InputTuple, DisputeClearedEvent.OutputTuple, DisputeClearedEvent.OutputObject>;
      DisputeCleared: TypedContractEvent<DisputeClearedEvent.InputTuple, DisputeClearedEvent.OutputTuple, DisputeClearedEvent.OutputObject>;
    

      'OutcomeDisputed(bytes32,address)': TypedContractEvent<OutcomeDisputedEvent.InputTuple, OutcomeDisputedEvent.OutputTuple, OutcomeDisputedEvent.OutputObject>;
      OutcomeDisputed: TypedContractEvent<OutcomeDisputedEvent.InputTuple, OutcomeDisputedEvent.OutputTuple, OutcomeDisputedEvent.OutputObject>;
    

      'OutcomeFinalized(bytes32,uint8)': TypedContractEvent<OutcomeFinalizedEvent.InputTuple, OutcomeFinalizedEvent.OutputTuple, OutcomeFinalizedEvent.OutputObject>;
      OutcomeFinalized: TypedContractEvent<OutcomeFinalizedEvent.InputTuple, OutcomeFinalizedEvent.OutputTuple, OutcomeFinalizedEvent.OutputObject>;
    

      'OutcomeProposed(bytes32,uint8,address,uint256,bytes32,bytes32)': TypedContractEvent<OutcomeProposedEvent.InputTuple, OutcomeProposedEvent.OutputTuple, OutcomeProposedEvent.OutputObject>;
      OutcomeProposed: TypedContractEvent<OutcomeProposedEvent.InputTuple, OutcomeProposedEvent.OutputTuple, OutcomeProposedEvent.OutputObject>;
    
    };
  }