/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace PredictionMarket {
      
    export type MarketConfigStruct = {matchId: BytesLike, usdc: AddressLike, matchSettlement: AddressLike, feeCollector: AddressLike, feeBps: BigNumberish, bScore: BigNumberish, outcomesCount: BigNumberish}

    export type MarketConfigStructOutput = [matchId: string, usdc: string, matchSettlement: string, feeCollector: string, feeBps: bigint, bScore: bigint, outcomesCount: bigint] & {matchId: string, usdc: string, matchSettlement: string, feeCollector: string, feeBps: bigint, bScore: bigint, outcomesCount: bigint }
  
    }

  export interface PredictionMarketInterface extends Interface {
    getFunction(nameOrSignature: "bScore" | "buy" | "feeBps" | "feeCollector" | "getOutcome" | "initialize" | "initialized" | "matchId" | "matchSettlement" | "outcomesCount" | "price" | "quoteBuy" | "quoteSell" | "redeem" | "sell" | "shares" | "totalShares" | "usdc"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "Initialized" | "Redeemed" | "Trade"): EventFragment;

    encodeFunctionData(functionFragment: 'bScore', values?: undefined): string;
encodeFunctionData(functionFragment: 'buy', values: [BigNumberish, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'feeBps', values?: undefined): string;
encodeFunctionData(functionFragment: 'feeCollector', values?: undefined): string;
encodeFunctionData(functionFragment: 'getOutcome', values?: undefined): string;
encodeFunctionData(functionFragment: 'initialize', values: [PredictionMarket.MarketConfigStruct]): string;
encodeFunctionData(functionFragment: 'initialized', values?: undefined): string;
encodeFunctionData(functionFragment: 'matchId', values?: undefined): string;
encodeFunctionData(functionFragment: 'matchSettlement', values?: undefined): string;
encodeFunctionData(functionFragment: 'outcomesCount', values?: undefined): string;
encodeFunctionData(functionFragment: 'price', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'quoteBuy', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'quoteSell', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'redeem', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'sell', values: [BigNumberish, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'shares', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'totalShares', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'usdc', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'bScore', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'buy', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'feeBps', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'feeCollector', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getOutcome', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'initialize', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'initialized', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'matchId', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'matchSettlement', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'outcomesCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'price', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'quoteBuy', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'quoteSell', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'redeem', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'sell', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'shares', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalShares', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'usdc', data: BytesLike): Result;
  }

  
    export namespace InitializedEvent {
      export type InputTuple = [matchId: BytesLike, usdc: AddressLike, matchSettlement: AddressLike, feeCollector: AddressLike, feeBps: BigNumberish, bScore: BigNumberish, outcomesCount: BigNumberish];
      export type OutputTuple = [matchId: string, usdc: string, matchSettlement: string, feeCollector: string, feeBps: bigint, bScore: bigint, outcomesCount: bigint];
      export interface OutputObject {matchId: string, usdc: string, matchSettlement: string, feeCollector: string, feeBps: bigint, bScore: bigint, outcomesCount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RedeemedEvent {
      export type InputTuple = [trader: AddressLike, outcome: BigNumberish, shares: BigNumberish, payout: BigNumberish];
      export type OutputTuple = [trader: string, outcome: bigint, shares: bigint, payout: bigint];
      export interface OutputObject {trader: string, outcome: bigint, shares: bigint, payout: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TradeEvent {
      export type InputTuple = [trader: AddressLike, outcome: BigNumberish, sharesDelta: BigNumberish, cost: BigNumberish, fee: BigNumberish];
      export type OutputTuple = [trader: string, outcome: bigint, sharesDelta: bigint, cost: bigint, fee: bigint];
      export interface OutputObject {trader: string, outcome: bigint, sharesDelta: bigint, cost: bigint, fee: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface PredictionMarket extends BaseContract {
    
    connect(runner?: ContractRunner | null): PredictionMarket;
    waitForDeployment(): Promise<this>;

    interface: PredictionMarketInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    bScore: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    buy: TypedContractMethod<
      [outcome: BigNumberish, amountShares: BigNumberish, maxCost: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    feeBps: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    feeCollector: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    getOutcome: TypedContractMethod<
      [],
      [[boolean, bigint] & {finalized: boolean, outcome: bigint }],
      'view'
    >
    

    
    initialize: TypedContractMethod<
      [config: PredictionMarket.MarketConfigStruct, ],
      [void],
      'nonpayable'
    >
    

    
    initialized: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    matchId: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    matchSettlement: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    outcomesCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    price: TypedContractMethod<
      [outcome: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    quoteBuy: TypedContractMethod<
      [outcome: BigNumberish, amountShares: BigNumberish, ],
      [[bigint, bigint] & {costUsdc: bigint, feeUsdc: bigint }],
      'view'
    >
    

    
    quoteSell: TypedContractMethod<
      [outcome: BigNumberish, amountShares: BigNumberish, ],
      [[bigint, bigint] & {proceedsUsdc: bigint, feeUsdc: bigint }],
      'view'
    >
    

    
    redeem: TypedContractMethod<
      [outcome: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    sell: TypedContractMethod<
      [outcome: BigNumberish, amountShares: BigNumberish, minProceeds: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    shares: TypedContractMethod<
      [arg0: AddressLike, arg1: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    totalShares: TypedContractMethod<
      [arg0: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    usdc: TypedContractMethod<
      [],
      [string],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'bScore'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'buy'): TypedContractMethod<
      [outcome: BigNumberish, amountShares: BigNumberish, maxCost: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'feeBps'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'feeCollector'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getOutcome'): TypedContractMethod<
      [],
      [[boolean, bigint] & {finalized: boolean, outcome: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'initialize'): TypedContractMethod<
      [config: PredictionMarket.MarketConfigStruct, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'initialized'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'matchId'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'matchSettlement'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'outcomesCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'price'): TypedContractMethod<
      [outcome: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'quoteBuy'): TypedContractMethod<
      [outcome: BigNumberish, amountShares: BigNumberish, ],
      [[bigint, bigint] & {costUsdc: bigint, feeUsdc: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'quoteSell'): TypedContractMethod<
      [outcome: BigNumberish, amountShares: BigNumberish, ],
      [[bigint, bigint] & {proceedsUsdc: bigint, feeUsdc: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'redeem'): TypedContractMethod<
      [outcome: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'sell'): TypedContractMethod<
      [outcome: BigNumberish, amountShares: BigNumberish, minProceeds: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'shares'): TypedContractMethod<
      [arg0: AddressLike, arg1: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'totalShares'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'usdc'): TypedContractMethod<
      [],
      [string],
      'view'
    >;

    getEvent(key: 'Initialized'): TypedContractEvent<InitializedEvent.InputTuple, InitializedEvent.OutputTuple, InitializedEvent.OutputObject>;
getEvent(key: 'Redeemed'): TypedContractEvent<RedeemedEvent.InputTuple, RedeemedEvent.OutputTuple, RedeemedEvent.OutputObject>;
getEvent(key: 'Trade'): TypedContractEvent<TradeEvent.InputTuple, TradeEvent.OutputTuple, TradeEvent.OutputObject>;

    filters: {
      
      'Initialized(bytes32,address,address,address,uint16,uint256,uint8)': TypedContractEvent<InitializedEvent.InputTuple, InitializedEvent.OutputTuple, InitializedEvent.OutputObject>;
      Initialized: TypedContractEvent<InitializedEvent.InputTuple, InitializedEvent.OutputTuple, InitializedEvent.OutputObject>;
    

      'Redeemed(address,uint8,uint256,uint256)': TypedContractEvent<RedeemedEvent.InputTuple, RedeemedEvent.OutputTuple, RedeemedEvent.OutputObject>;
      Redeemed: TypedContractEvent<RedeemedEvent.InputTuple, RedeemedEvent.OutputTuple, RedeemedEvent.OutputObject>;
    

      'Trade(address,uint8,uint256,uint256,uint256)': TypedContractEvent<TradeEvent.InputTuple, TradeEvent.OutputTuple, TradeEvent.OutputObject>;
      Trade: TypedContractEvent<TradeEvent.InputTuple, TradeEvent.OutputTuple, TradeEvent.OutputObject>;
    
    };
  }