/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { IMatchSettlement, IMatchSettlementInterface } from "../../interfaces/IMatchSettlement.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "bytes32",
        "name": "matchId",
        "type": "bytes32"
      }
    ],
    "name": "getOutcome",
    "outputs": [
      {
        "internalType": "bool",
        "name": "finalized",
        "type": "bool"
      },
      {
        "internalType": "uint8",
        "name": "outcome",
        "type": "uint8"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  }
] as const;

  export class IMatchSettlement__factory {
    static readonly abi = _abi;
    static createInterface(): IMatchSettlementInterface {
      return new Interface(_abi) as IMatchSettlementInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): IMatchSettlement {
      return new Contract(address, _abi, runner) as unknown as IMatchSettlement;
    }
  }
  